addSbtPlugin("com.codecommit" % "sbt-github-actions" % "0.14.2")
addSbtPlugin("com.github.sbt" % "sbt-unidoc" % "0.5.0")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.5.10")
// addSbtPlugin("com.github.sbt"   % "sbt-git"             % "2.0.0")
addSbtPlugin("org.lyranthe.sbt" % "partial-unification" % "1.1.2")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.3.2")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.9.3")
// addSbtPlugin("com.eed3si9n" % "sbt-projectmatrix" % "0.8.0")

addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.15.0")
