addSbtPlugin("com.codecommit"   % "sbt-github-actions"  % "0.14.2")
addSbtPlugin("com.github.sbt"   % "sbt-unidoc"          % "0.5.0")
addSbtPlugin("com.github.sbt"   % "sbt-ci-release"      % "1.5.10")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"             % "1.0.2")
addSbtPlugin("org.lyranthe.sbt" % "partial-unification" % "1.1.2")
addSbtPlugin("org.scalameta"    % "sbt-mdoc"            % "2.3.1")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"       % "1.9.2")
