addSbtPlugin("com.github.sbt" % "sbt-github-actions" % "0.24.0")
addSbtPlugin("com.github.sbt" % "sbt-unidoc" % "0.5.0")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.5.10")
// addSbtPlugin("com.github.sbt"   % "sbt-git"             % "2.0.0")
addSbtPlugin("org.lyranthe.sbt" % "partial-unification" % "1.1.2")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.3.5")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "2.0.0")
// addSbtPlugin("com.eed3si9n" % "sbt-projectmatrix" % "0.8.0")

addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.7.1")
